name: Check for update and release

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 10 * * *'

jobs:
  call-workflow:
    uses: thespad/actions/.github/workflows/ci.yml@v2
    with:
      repo_owner: ${{ github.repository_owner }}
      app_name: "changedetection.io"
      release_type: "github"
      release_url: "https://api.github.com/repos/dgtlmoon/changedetection.io/releases/latest"
    secrets:
      repo_scoped_token: ${{ secrets.repo_scoped_token }}