name: Build Image On Release

on:
  release:
    types: [published]
  pull_request:

jobs:
  call-workflow:
    uses: thespad/actions/.github/workflows/build-image.yml@v6
    with:
      repo_owner: "thespad"
      app_name: "changedetection.io"
      release_type: "github"
      release_url: "https://api.github.com/repos/dgtlmoon/changedetection.io"
      dockerhub_user: "thespad"
      target-arch: "all"      
    secrets:
      dockerhub_password: ${{ secrets.DOCKER_PASSWORD }}
