name: Check for update and release

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 10 * * *'

jobs:
  call-workflow:
    uses: thespad/actions/.github/workflows/check-and-release.yml@v6
    with:
      repo_owner: "thespad"
      app_name: "changedetection.io"
      release_type: "github"
      release_url: "https://api.github.com/repos/dgtlmoon/changedetection.io"
    secrets:
      repo_scoped_token: ${{ secrets.repo_scoped_token }}
