#!/usr/bin/with-contenv bash

cat <<-EOF
    ***************************************************************
    ***************************************************************
    *                                                             *
    *                             !!!!                            *
    *        This image is no longer supported, switch to:        *
    *  https://github.com/linuxserver/docker-changedetection.io   *
    *                   as a direct replacement.                  *
    *                                                             *
    *                                                             *    
    ***************************************************************
    ***************************************************************
EOF
